# These are supported funding model platforms

github: [daretechie] # Replace with your GitHub username
# patreon: your_patreon_username
# open_collective: your_collective_name
# ko_fi: your_ko_fi_name
# tidelift: "npm/your-package-name"
# community_bridge: your_project_name
# liberapay: your_username
# issuehunt: your_username
# litchi: your_username
# custom: ["https://www.paypal.me/yourname"]
