"""Initial migration

Revision ID: 6618f1ff6aa9
Revises:
Create Date: 2026-01-25 08:02:40.978278

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6618f1ff6aa9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_history",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slack_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("git_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("total_commitments", sa.Integer(), nullable=False),
        sa.Column("failed_commitments", sa.Integer(), nullable=False),
        sa.Column("reliability_score", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_user_history_user_id"), "user_history", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_history_user_id"), table_name="user_history")
    op.drop_table("user_history")
    # ### end Alembic commands ###
