"""fresh_schema_with_personas

Revision ID: 711eaaaee0cc
Revises: 
Create Date: 2026-01-29 18:30:23.858889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '711eaaaee0cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cultural_personas',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_cultural_personas_code'), 'cultural_personas', ['code'], unique=False)
    op.create_table('safety_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manager_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_taken', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('final_message_sent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feedback_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_feedback_intervention_id'), 'safety_feedback', ['intervention_id'], unique=False)
    op.create_index(op.f('ix_safety_feedback_user_id'), 'safety_feedback', ['user_id'], unique=False)
    op.create_table('safety_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hr_keywords', sa.JSON(), nullable=True),
    sa.Column('semantic_rules', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('onboarded_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_rules_department'), 'safety_rules', ['department'], unique=False)
    op.create_index(op.f('ix_safety_rules_industry'), 'safety_rules', ['industry'], unique=False)
    op.create_table('user_history',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slack_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('git_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_commitments', sa.Integer(), nullable=False),
    sa.Column('failed_commitments', sa.Integer(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('industry_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_context_verified', sa.Boolean(), nullable=False),
    sa.Column('language_preference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consecutive_firm_interventions', sa.Integer(), nullable=False),
    sa.Column('last_intervention_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_history_department'), 'user_history', ['department'], unique=False)
    op.create_index(op.f('ix_user_history_git_email'), 'user_history', ['git_email'], unique=False)
    op.create_index(op.f('ix_user_history_slack_id'), 'user_history', ['slack_id'], unique=False)
    op.create_index(op.f('ix_user_history_user_id'), 'user_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_history_user_id'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_slack_id'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_git_email'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_department'), table_name='user_history')
    op.drop_table('user_history')
    op.drop_index(op.f('ix_safety_rules_industry'), table_name='safety_rules')
    op.drop_index(op.f('ix_safety_rules_department'), table_name='safety_rules')
    op.drop_table('safety_rules')
    op.drop_index(op.f('ix_safety_feedback_user_id'), table_name='safety_feedback')
    op.drop_index(op.f('ix_safety_feedback_intervention_id'), table_name='safety_feedback')
    op.drop_table('safety_feedback')
    op.drop_index(op.f('ix_cultural_personas_code'), table_name='cultural_personas')
    op.drop_table('cultural_personas')
    # ### end Alembic commands ###
