from datetime import datetime, timezone
from src.schemas.agents import UserHistory, ReportSummary, AggregateReport
from src.schemas.performance import SlippageAnalysis, TruthGapAnalysis


class AuditReportGenerator:
    """
    The 'Cash Generator': Turns raw database data and agent analysis into a
    professional PDF/JSON report that can be sold as a service.
    """

    @staticmethod
    def generate_audit_summary(
        user: UserHistory, slippage: SlippageAnalysis, truth_gap: TruthGapAnalysis
    ) -> ReportSummary:
        """
        Creates a high-value 'Performance Integrity Audit' for a manager.
        """
        return ReportSummary(
            report_id=f"AUDIT-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}-{user.user_id}",
            generated_at=datetime.now(timezone.utc).isoformat(),
            subject={
                "user_id": user.user_id,
                "reliability_score": f"{user.reliability_score:.2f}%",
                "total_commitments": user.total_commitments,
            },
            performance_metrics={
                "status": slippage.status,
                "fulfillment_ratio": f"{slippage.fulfillment_ratio * 100:.2f}%",
                "detected_gap": slippage.detected_gap,
            },
            integrity_score={
                "aligned": not truth_gap.gap_detected,
                "truth_score": f"{truth_gap.truth_score * 100:.2f}%",
                "explanation": truth_gap.explanation,
            },
            intervention_recommendation={
                "required": slippage.intervention_required or truth_gap.gap_detected,
                "tone": truth_gap.recommended_tone,
                "summary": "High risk of technical debt accumulation detected."
                if truth_gap.gap_detected
                else "Maintain current performance.",
            },
        )

    @staticmethod
    def generate_markdown_audit(report: ReportSummary) -> str:
        """
        Turns a ReportSummary into a high-impact professional Markdown document.
        """
        return f"""# 🛡️ Performance Integrity Audit: {report.subject["user_id"]}
**Report ID**: `{report.report_id}` | **Date**: {report.generated_at[:10]}

---

## 📊 Summary Scorecard
| Metric | Value |
| :--- | :--- |
| **Reliability Score** | **{report.subject["reliability_score"]}** |
| **Total Commitments** | {report.subject["total_commitments"]} |
| **Fulfillment Ratio** | {report.performance_metrics["fulfillment_ratio"]} |
| **Integrity Alignment** | {"✅ ALIGNED" if report.integrity_score["aligned"] else "⚠️ GAP DETECTED"} |

---

## 🔍 Performance Deep-Dive
**Status**: `{report.performance_metrics["status"]}`

### Commitment fulfillment
The subject has demonstrated a **{report.performance_metrics["fulfillment_ratio"]}** fulfillment rate.
**Detected Gaps**: {report.performance_metrics["detected_gap"]}

### Truth-Gap Analysis
**Confidence Score**: {report.integrity_score["truth_score"]}
{report.integrity_score["explanation"]}

---

## 🛠️ Management Strategy
**Intervention Required**: **{"YES" if report.intervention_recommendation["required"] else "NO"}**
**Recommended Tone**: `{report.intervention_recommendation["tone"]}`

### Manager Summary
{report.intervention_recommendation["summary"]}

---
*Generated by CommitVigil - Elite Accountability Infrastructure*
"""

    @staticmethod
    def generate_html_audit(report: ReportSummary) -> str:
        """
        Creates a premium, glassmorphic HTML report that renders perfectly to PDF.
        """
        aligned_color = "#10b981" if report.integrity_score["aligned"] else "#ef4444"
        return f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>CommitVigil Audit - {report.subject["user_id"]}</title>
    <style>
        :root {{
            --primary: #6366f1;
            --bg: #0f172a;
            --card-bg: rgba(30, 41, 59, 0.7);
            --text: #f8fafc;
        }}
        body {{
            font-family: 'Inter', -apple-system, sans-serif;
            background: var(--bg);
            color: var(--text);
            margin: 0;
            padding: 40px;
            line-height: 1.6;
        }}
        .container {{
            max-width: 800px;
            margin: auto;
            background: var(--card-bg);
            padding: 40px;
            border-radius: 24px;
            border: 1px solid rgba(255,255,255,0.1);
            backdrop-filter: blur(10px);
            box-shadow: 0 25px 50px -12px rgba(0,0,0,0.5);
        }}
        .header {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 40px;
            border-bottom: 1px solid rgba(255,255,255,0.1);
            padding-bottom: 20px;
        }}
        h1 {{ margin: 0; font-size: 24px; letter-spacing: -0.025em; }}
        .badge {{
            padding: 6px 12px;
            border-radius: 99px;
            font-size: 12px;
            font-weight: 600;
            text-transform: uppercase;
        }}
        .score-card {{
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 20px;
            margin-bottom: 40px;
        }}
        .metric {{
            background: rgba(255,255,255,0.05);
            padding: 20px;
            border-radius: 16px;
            text-align: center;
        }}
        .metric-val {{ font-size: 32px; font-weight: 700; color: var(--primary); }}
        .metric-label {{ font-size: 12px; opacity: 0.6; text-transform: uppercase; }}
        .section-title {{
            font-size: 14px;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.1em;
            color: var(--primary);
            margin-bottom: 16px;
        }}
        .strategy-box {{
            background: linear-gradient(135deg, rgba(99, 102, 241, 0.1), rgba(168, 85, 247, 0.1));
            padding: 24px;
            border-radius: 16px;
            border: 1px solid rgba(99, 102, 241, 0.2);
        }}
        @media print {{
            body {{ background: white; color: black; padding: 0; }}
            .container {{ border: none; box-shadow: none; background: white; }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div>
                <h1>🛡️ PERFORMANCE AUDIT</h1>
                <small style="opacity: 0.5">Report ID: {report.report_id}</small>
            </div>
            <div class="badge" style="background: {aligned_color}22; color: {aligned_color}; border: 1px solid {aligned_color}44">
                {"Aligned" if report.integrity_score["aligned"] else "Gap Detected"}
            </div>
        </div>

        <div class="score-card">
            <div class="metric">
                <div class="metric-val">{report.subject["reliability_score"]}</div>
                <div class="metric-label">Reliability Score</div>
            </div>
            <div class="metric">
                <div class="metric-val">{report.performance_metrics["fulfillment_ratio"]}</div>
                <div class="metric-label">Fulfillment Rate</div>
            </div>
        </div>

        <div class="section-title">Analysis Summary</div>
        <p><strong>Status:</strong> {report.performance_metrics["status"]}</p>
        <p>{report.integrity_score["explanation"]}</p>

        <div style="margin-top: 40px;">
            <div class="section-title">Management Strategy</div>
            <div class="strategy-box">
                <p style="margin-top: 0"><strong>Recommended Tone:</strong> <span class="badge" style="background: rgba(255,255,255,0.1)">{report.intervention_recommendation["tone"]}</span></p>
                <p style="margin-bottom: 0">{report.intervention_recommendation["summary"]}</p>
            </div>
        </div>
        <div style="margin-top: 60px; text-align: center; font-size: 10px; opacity: 0.3;">
            GENERATED BY COMMITVIGIL &bull; ENTERPRISE GRADE ACCOUNTABILITY
        </div>
    </div>
</body>
</html>
"""

    @staticmethod
    def generate_departmental_audit(
        department: str, members: list[UserHistory], intervention_rate: float
    ) -> AggregateReport:
        """
        Enterprise Feature: Aggregates performance data for 100+ user departments.
        Identifies systemic burnout and top-tier reliability.
        """
        if not members:
            # Fallback for empty departments
            return AggregateReport(
                department=department,
                total_members=0,
                average_reliability_score=100.0,
                burnout_risk_count=0,
                top_performers=[],
                critical_risk_members=[],
                intervention_acceptance_rate=intervention_rate,
            )

        total_rel = sum(m.reliability_score for m in members)
        avg_rel = round(total_rel / len(members), 2)

        top_perf = [m.user_id for m in members if m.reliability_score >= 90.0][
            :5
        ]  # Top 5
        critical = [m.user_id for m in members if m.reliability_score < 50.0][
            :5
        ]  # Bottom 5

        # Heuristic: If reliability is dropping rapidly across the team, flag it.
        # For this demo, we'll assume a static check.
        burnout = len([m for m in members if m.reliability_score < 70.0])

        return AggregateReport(
            department=department,
            total_members=len(members),
            average_reliability_score=avg_rel,
            burnout_risk_count=burnout,
            top_performers=top_perf,
            critical_risk_members=critical,
            intervention_acceptance_rate=intervention_rate,
        )
